---
title: "Gov 50 Final Project"
author: "Maya O'Dea"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to sports or fashion. Whether it be data relating to sports performance or fashion trends, both industries are intriguing and use data science in different ways. 

## Proposal

Do Super Bowl commercials not showing their product quickly overuse marketing strategies? In this study, I plan to examine the use marketing strategies of Super Bowl commercials, focusing on the amount of categories these ads present, and if the product is shown quick enough. There are six popular strategies of marketing categories: Funny, Patriotic, Celebrity, Danger, Animals, and Sex. I want to explore commercials that didn't show their product in the first 10 seconds and if two or more marketing strategies were used in the ad. I hypothesize many Super Bowl commercials partake in this trend to grab their viewer's attention. Using several strategies creates more of an ostentatious and memorable commercial, which is the goal of showing one at the Super Bowl. My sample is made up of various product commercials during the Super Bowl from several different years, along with True/False data under each of the six marketing strategy categories and the shown quickly variable. My units of analysis are commercials that didn't show a product in the first 10 seconds. My outcome variable is the the number of marketing strategy categories marked true. This will be measured first by count of how many categories each commercial marked true and then the proportion of those using two or more categories and those using less. If the proportion of commercials not showing the product in the first 10 seconds is greater when using two or more categories, then my hypothesis is correct. However if the proportion of those using less than two strategies is greater, then there is evidence against my hypothesis. 












